### PR TITLE
Move jekyll functionality from makefile to grunt

### PR DESCRIPTION
**Pull request by crccheck**
To unify the interface and make it so you need fewer windows open, this PR moves the jekyll functionality from the makefile shortcut to grunt. I tried this using `grunt-jekyll` but it sucked. Based on a conversation at ATXSass, I tried again using a shell task.
#### Testing
1. `npm install` to update requirements
2. `grunt dev` to start watcher and server
3. open the jekyll site in your browser, probably http://localhost:4000/
4. make a trivial css, change. I added `background: mediumpurple !important;` to the html
5. check to see that everything is purple
6. make a trivial html change. I added `moo` to the beginning of `_includes/nav.html`
7. check to see that you're mooing
#### Next?

there's a grunt task for automagically opening the browser too, but I think that's going too far.
#### Smells

There's some code I thought I might need/want but I don't think we'll ever use it. See the "`jekyllWatch` is not used, but here for reference" comment

### CODE REVIEW

**Comment by kabeaty** [comment]
Just tried this out, and the live reload isn't working when I make changes to the HTML/CSS, but does work on manual reload. Other than that, looks good to me. Also, should we update the README in this PR to get rid of the 'Running Jekyll' section?

**Comment by crccheck** [comment]
I made an update to the readme in 9c21549 to adapt the 'Running Jekyll' section. I haven't been using livereload so I'll have to check.

Running Jackal

**Comment by crccheck** [comment]
Livereload works for me when editing sass. I just added support to the html files to livereload.

**Comment by risatrix** [comment]
Live reload not working for me either. Does it require a browser plugin like the old one? (I have it installed, if that matters).

Otherwise, works as advertised.

**Comment by crccheck** [comment]
you're going to have to show me what your definition of livereload is. what's "the old one"?

**Comment by risatrix** [comment]
The [old one](https://github.com/gruntjs/grunt-contrib-livereload) was the separate live reload, deprecated in favor of watch, which doesn't say it needs anything extra. But of course such details are often accidentally left out.

**Comment by kabeaty** [comment]
+1 on my end for merging this in btw

**Comment by risatrix** [comment]
Seconded. The live reload isn't a big deal on my end.

**Pull request merged**
